apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: prod
replicas:
- count: 2
  name: java-app
images:
- name: ghcr.io/sajjadkhan12/complete-app-cicd/java-app
  newName: ghcr.io/sajjadkhan12/complete-app-cicd/java-app
  newTag: e50ec35
