apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sajjadkhan12/complete-app-cicd.git
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app-stg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sajjadkhan12/complete-app-cicd.git
    targetRevision: HEAD
    path: k8s/overlays/stg
  destination:
    server: https://kubernetes.default.svc
    namespace: stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sajjadkhan12/complete-app-cicd.git
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
