apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: dev
images:
- name: ghcr.io/sajjadkhan12/complete-app-cicd/java-app
  newName: ghcr.io/sajjadkhan12/complete-app-cicd/java-app
  newTag: a2ec96a
